### ISSUE TITLE
Would plan to intergrate this toolkit into rdkit like shape-it?

### ISSUE THREAD

**Issue by ClinuxMDL** [iwatobipen/align-it-ob3#1]
Hi, 

Thank you for your blogs about intrduction of shape-it and align-it. It would help me a lot. For ligand-based virtual screening, which one you prefer to use? Maybe the hybird score is a better strategy? 
I wonder know whether align-it is planning to be intergated into the rdkit like  shape-it?  

Best regards,
YJ

**Comment by iwatobipen** [comment]
Hi YJ,
Thanks for your comment.
Sure it will be useful I think too. Because align-it is pharmacophore based and shape-it is shape based. Both methods are different but useful.
I use both tools and it depends on situation.
I would like to align-it to rdkit if I could have enough time.
Thanks,
Taka
